//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAccountingСomponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.IssueRegistrationLog = new HashSet<IssueRegistrationLog>();
        }
    
        public int id { get; set; }
        public int id_type_equipment { get; set; }
        public string serial_number { get; set; }
        public decimal cost { get; set; }
        public System.DateTime purchase_date { get; set; }
        public int id_financially_responsible_person { get; set; }
        public int id_departament { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual FinanciallyResponsiblePersons FinanciallyResponsiblePersons { get; set; }
        public virtual TypesOfEquipment TypesOfEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueRegistrationLog> IssueRegistrationLog { get; set; }
    }
}
