//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAccountingСomponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueRegistrationLog
    {
        public int id { get; set; }
        public int id_equipment { get; set; }
        public int id_employee { get; set; }
        public System.DateTime data_references { get; set; }
        public Nullable<System.DateTime> date_of_return { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
